server:
  port: 8081  # 端口号
  servlet:
    context-path: /   #项目根路径（前面必须加/）

spring:
  # Mysql配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://127.0.0.1:3306/hola?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

      # 其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,slf4j
      db-type: mysql
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#logging:
#  file:
#    path: /usr/local/logs
#  level:
#    com.zengyanyu.system: debug
#    org.springframework: warn
#    springfox: error

file:
  uploadFolder: D:/upload/
  uploadH5Folder: D:/uploadH5/

# ==================== Excel导入配置 ====================
excel:
  import:
    # 定时任务cron表达式：每10秒执行一次
    cron: "0/5 * * * * ?"
    # 根扫描目录
    scan-path: E:/excel
    is-started: false
    # 文件夹名称 -> 对应Service的Bean名称 映射
    folder-service-map:
      data-dict: dictService    # user-data文件夹 → 用户数据导入服务
      product-data: productImportExcelService # 新增业务直接加配置
    # 默认服务（未匹配到文件夹时使用）
    default-service: defaultImportExcelService

# ==================== 线程池配置 ====================
executor:
  core-size: 5
  max-size: 10
  queue-capacity: 20
  keep-alive-seconds: 60
